import { createContext, useContext, useState, useCallback, useMemo, type ReactNode, type Context } from "react";

export type Language = "pt" | "en" | "es" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const defaultLanguage: Language = "pt";

const translations: Record<Language, Record<string, string>> = {
  pt: {
    "header.title": "Cardápio Acessível",
    "header.table": "Mesa",
    "category.entrada": "Entradas",
    "category.prato": "Pratos Principais",
    "category.acompanhamento": "Acompanhamentos",
    "category.bebidas": "Bebidas",
    "category.sobremesa": "Sobremesas",
    "category.outros": "Outros",
    "category.cafe_espresso": "Café Espresso",
    "category.chocolate": "Chocolate",
    "category.empanada_salgado": "Empanada e Salgado",
    "category.metodos_extracao": "Métodos de Extração",
    "category.paulistinha": "Paulistinha",
    "category.waffles": "Waffles",
    "category.almoco": "Almoço",
    "category.espresso_gelado": "Espresso Gelado",
    "category.chocolate_gelado": "Chocolate Gelado",
    "category.drinks_sem_alcool": "Drinks sem Álcool",
    "category.chai_latte": "Chai-Latte",
    "category.chas": "Chás",
    "category.drinks_especiais": "Drinks Especiais",
    "category.cervejas": "Cervejas",
    "filter.all": "Todos",
    "filter.pratos": "Pratos Principais",
    "filter.findFavorite": "Encontre sua opção favorita",
    "filter.bebidas": "Bebidas",
    "filter.sobremesas": "Sobremesas",
    "filter.outros": "Outros",
    "empty.title": "Nenhum item disponível no momento.",
    "empty.subtitle": "Acesse /admin/gestao para cadastrar itens.",
    "audio": "Áudio",
    "audio.description": "Escutar descrição do item de cardápio",
    "audio.play": "Ouvir áudio",
    "audio.pause": "Pausar áudio",
    "audio.resume": "Retomar áudio",
    "audio.unavailable": "Áudio indisponível",
    "audio.aria.listen": "Escutar o item de cardápio",
    "audio.aria.pause": "Pausar a leitura por voz do item de cardápio",
    "audio.aria.resume": "Retomar a leitura por voz do item de cardápio",
    "audio.aria.unavailable": "Leitura por voz indisponível para este item do cardápio",
    "audio.status.ready": "Áudio pronto para reprodução.",
    "audio.status.playing": "Áudio em reprodução.",
    "audio.status.paused": "Áudio pausado.",
    "audio.status.unavailable": "Leitura por voz indisponível neste navegador.",
    "libras": "Libras",
    "libras.description": "Ver tradução em Libras do item",
    "allergen.gluten": "Glúten",
    "allergen.lactose": "Lactose",
    "allergen.nuts": "Nozes",
    "allergen.soy": "Soja",
    "allergen.eggs": "Ovos",
    "allergen.fish": "Peixe",
    "allergen.shellfish": "Frutos do mar",
    "accessibility.title": "Acessibilidade",
    "accessibility.increase_font": "Aumentar fonte",
    "accessibility.decrease_font": "Diminuir fonte",
    "accessibility.high_contrast": "Alto contraste",
    "accessibility.grayscale": "Escala de cinza",
    "accessibility.dyslexia_font": "Fonte para dislexia",
    "accessibility.reset": "Restaurar padrão",
    "accessibility.open": "Abrir acessibilidade",
    "accessibility.open.description": "Abrir painel de opções de acessibilidade",
    "accessibility.close": "Fechar painel de acessibilidade",
    "waiter.call": "Chamar Garçom",
    "waiter.call.table": "Chamar Garçom — Mesa",
    "waiter.called": "Garçom chamado!",
    "waiter.calling": "Chamando...",
    "waiter.already_called": "Garçom já foi chamado para esta mesa.",
    "language": "Idioma",
    "language.options": "Opções de idioma do cardápio",
    "language.select": "Selecionar idioma do cardápio",
    "ingredients.image.button": "Ver ingredientes",
    "ingredients.image.aria": "Visualizar ingredientes do prato em formato de imagem:",
    "ingredients.image.loading": "Gerando imagem dos ingredientes...",
    "ingredients.image.error": "Não foi possível gerar a imagem. Tente novamente.",
    "ingredients.image.modal.title": "Ingredientes",
    "ingredients.image.modal.close": "Fechar modal de ingredientes",
    "ingredients.image.alt": "Ilustração dos ingredientes do prato",
    "tutorial.button": "Como usar",
    "tutorial.title": "Como usar o cardápio",
    "tutorial.close": "Fechar vídeo",
    "tutorial.play": "Reproduzir vídeo",
    "tutorial.pause": "Pausar vídeo",
    "tutorial.stop": "Reiniciar vídeo",
    "tutorial.mute": "Silenciar",
    "tutorial.unmute": "Ativar som",
    "tutorial.speed": "Alterar velocidade do vídeo",
    "tutorial.modal.aria": "Assistir vídeo explicativo sobre como usar o cardápio acessível",
    "tutorial.prompt": "Veja como usar o cardápio acessível",
    "tutorial.watchNow": "Ver agora",
    "tutorial.later": "Depois",
    "tutorial.watchNow.aria": "Ver o vídeo como usar o cardápio acessível",
    "tutorial.later.aria": "Ver depois o vídeo como usar o cardápio acessível",
    "tutorial.aria.started": "Vídeo iniciado. Use Tab para navegar nos controles.",
    "tutorial.aria.ready": "Vídeo pronto para reprodução. Use Tab para navegar nos controles.",
    "tutorial.aria.playing": "Vídeo em reprodução.",
    "tutorial.aria.paused": "Vídeo pausado.",
    "tutorial.aria.stopped": "Vídeo reiniciado.",
    "tutorial.aria.ended": "Vídeo finalizado.",
    "tutorial.aria.controls": "Controles do player de vídeo",
    "welcome.title": "Bem-vindo ao Café Infinito Olhar ☕",
    "welcome.message": "Este é um cardápio acessível, pensado para oferecer uma experiência mais inclusiva, com recursos como áudio, ajustes de visualização e navegação simplificada.",
    "welcome.videoQuestion": "Quer saber como usar o cardápio?",
    "welcome.watchVideo": "Assistir vídeo explicativo",
    "welcome.goToMenu": "Ir direto para o cardápio",
    "welcome.listen": "Ouvir mensagem de boas-vindas",
    "welcome.stopListen": "Parar leitura",
    "welcome.close": "Fechar boas-vindas",
    "welcome.watchVideo.aria": "Assistir vídeo de como usar o cardápio",
    "welcome.goToMenu.aria": "Ir direto para o cardápio",
    "welcome.modal.aria": "Tela de boas-vindas do Café Infinito Olhar",
    "filter.aria.label": "Filtro de categorias do cardápio",
    "filter.aria.all": "Ver todos os itens do cardápio",
    "ingredients.image.figure_alt": "Figura com os ingredientes do prato",
    "accessibility.enabled": "ativado",
    "accessibility.disabled": "desativado",
    "accessibility.font_size": "Tamanho da fonte ajustado para",
    "accessibility.reset.done": "Configurações de acessibilidade restauradas ao padrão",
  },
  en: {
    "header.title": "Accessible Menu",
    "header.table": "Table",
    "category.entrada": "Starters",
    "category.prato": "Main Courses",
    "category.acompanhamento": "Side Dishes",
    "category.bebidas": "Drinks",
    "category.sobremesa": "Desserts",
    "category.outros": "Others",
    "category.cafe_espresso": "Espresso Coffee",
    "category.chocolate": "Chocolate",
    "category.empanada_salgado": "Empanadas & Savory Snacks",
    "category.metodos_extracao": "Brewing Methods",
    "category.paulistinha": "Paulistinha",
    "category.waffles": "Waffles",
    "category.almoco": "Lunch",
    "category.espresso_gelado": "Iced Espresso",
    "category.chocolate_gelado": "Iced Chocolate",
    "category.drinks_sem_alcool": "Non-Alcoholic Drinks",
    "category.chai_latte": "Chai Latte",
    "category.chas": "Teas",
    "category.drinks_especiais": "Special Drinks",
    "category.cervejas": "Beers",
    "filter.all": "All",
    "filter.pratos": "Main Courses",
    "filter.findFavorite": "Find your favorite option",
    "filter.bebidas": "Drinks",
    "filter.sobremesas": "Desserts",
    "filter.outros": "Others",
    "empty.title": "No items available at the moment.",
    "empty.subtitle": "Go to /admin/gestao to add items.",
    "audio": "Audio",
    "audio.description": "Listen to menu item description",
    "audio.play": "Play audio",
    "audio.pause": "Pause audio",
    "audio.resume": "Resume audio",
    "audio.unavailable": "Audio unavailable",
    "audio.aria.listen": "Listen to this menu item",
    "audio.aria.pause": "Pause the voice reading for this menu item",
    "audio.aria.resume": "Resume the voice reading for this menu item",
    "audio.aria.unavailable": "Voice reading is unavailable for this menu item",
    "audio.status.ready": "Audio ready to play.",
    "audio.status.playing": "Audio is playing.",
    "audio.status.paused": "Audio is paused.",
    "audio.status.unavailable": "Voice reading is unavailable in this browser.",
    "libras": "Sign Language",
    "libras.description": "View sign language translation",
    "allergen.gluten": "Gluten",
    "allergen.lactose": "Lactose",
    "allergen.nuts": "Nuts",
    "allergen.soy": "Soy",
    "allergen.eggs": "Eggs",
    "allergen.fish": "Fish",
    "allergen.shellfish": "Shellfish",
    "accessibility.title": "Accessibility",
    "accessibility.increase_font": "Increase font",
    "accessibility.decrease_font": "Decrease font",
    "accessibility.high_contrast": "High contrast",
    "accessibility.grayscale": "Grayscale",
    "accessibility.dyslexia_font": "Dyslexia font",
    "accessibility.reset": "Reset",
    "accessibility.open": "Open accessibility",
    "accessibility.open.description": "Open accessibility options panel",
    "accessibility.close": "Close accessibility panel",
    "waiter.call": "Call Waiter",
    "waiter.call.table": "Call Waiter — Table",
    "waiter.called": "Waiter called!",
    "waiter.calling": "Calling...",
    "waiter.already_called": "Waiter has already been called for this table.",
    "language": "Language",
    "language.options": "Menu language options",
    "language.select": "Select menu language",
    "ingredients.image.button": "View ingredients",
    "ingredients.image.aria": "View ingredients as image:",
    "ingredients.image.loading": "Generating ingredient image...",
    "ingredients.image.error": "Could not generate the image. Please try again.",
    "ingredients.image.modal.title": "Ingredients",
    "ingredients.image.modal.close": "Close ingredients modal",
    "ingredients.image.alt": "Illustration of the dish ingredients",
    "tutorial.button": "How to use",
    "tutorial.title": "How to use the menu",
    "tutorial.close": "Close video",
    "tutorial.play": "Play video",
    "tutorial.pause": "Pause video",
    "tutorial.stop": "Restart video",
    "tutorial.mute": "Mute",
    "tutorial.unmute": "Unmute",
    "tutorial.speed": "Change video speed",
    "tutorial.modal.aria": "Watch tutorial video on how to use the accessible menu",
    "tutorial.prompt": "Learn how to use the accessible menu",
    "tutorial.watchNow": "Watch now",
    "tutorial.later": "Later",
    "tutorial.watchNow.aria": "Watch the video on how to use the accessible menu",
    "tutorial.later.aria": "Watch later the video on how to use the accessible menu",
    "tutorial.aria.started": "Video started. Use Tab to navigate controls.",
    "tutorial.aria.ready": "Video ready to play. Use Tab to navigate controls.",
    "tutorial.aria.playing": "Video is playing.",
    "tutorial.aria.paused": "Video is paused.",
    "tutorial.aria.stopped": "Video restarted.",
    "tutorial.aria.ended": "Video ended.",
    "tutorial.aria.controls": "Video player controls",
    "welcome.title": "Welcome to Café Infinito Olhar ☕",
    "welcome.message": "This is an accessible menu, designed to offer a more inclusive experience, with features such as audio, display adjustments and simplified navigation.",
    "welcome.videoQuestion": "Want to learn how to use the menu?",
    "welcome.watchVideo": "Watch tutorial video",
    "welcome.goToMenu": "Go straight to the menu",
    "welcome.listen": "Listen to welcome message",
    "welcome.stopListen": "Stop reading",
    "welcome.close": "Close welcome",
    "welcome.watchVideo.aria": "Watch the video on how to use the menu",
    "welcome.goToMenu.aria": "Go straight to the menu",
    "welcome.modal.aria": "Café Infinito Olhar welcome screen",
    "filter.aria.label": "Menu category filter",
    "filter.aria.all": "View all menu items",
    "ingredients.image.figure_alt": "Image showing the dish ingredients",
    "accessibility.enabled": "enabled",
    "accessibility.disabled": "disabled",
    "accessibility.font_size": "Font size adjusted to",
    "accessibility.reset.done": "Accessibility settings reset to default",
  },
  es: {
    "header.title": "Menú Accesible",
    "header.table": "Mesa",
    "category.entrada": "Entradas",
    "category.prato": "Platos Principales",
    "category.acompanhamento": "Acompañamientos",
    "category.bebidas": "Bebidas",
    "category.sobremesa": "Postres",
    "category.outros": "Otros",
    "category.cafe_espresso": "Café Espresso",
    "category.chocolate": "Chocolate",
    "category.empanada_salgado": "Empanadas y Salados",
    "category.metodos_extracao": "Métodos de Extracción",
    "category.paulistinha": "Paulistinha",
    "category.waffles": "Waffles",
    "category.almoco": "Almuerzo",
    "category.espresso_gelado": "Espresso Helado",
    "category.chocolate_gelado": "Chocolate Helado",
    "category.drinks_sem_alcool": "Bebidas sin Alcohol",
    "category.chai_latte": "Chai-Latte",
    "category.chas": "Tés",
    "category.drinks_especiais": "Bebidas Especiales",
    "category.cervejas": "Cervezas",
    "filter.all": "Todos",
    "filter.pratos": "Platos Principales",
    "filter.findFavorite": "Encuentra tu opción favorita",
    "filter.bebidas": "Bebidas",
    "filter.sobremesas": "Postres",
    "filter.outros": "Otros",
    "empty.title": "No hay artículos disponibles en este momento.",
    "empty.subtitle": "Vaya a /admin/gestao para agregar artículos.",
    "audio": "Audio",
    "audio.description": "Escuchar descripción del artículo del menú",
    "audio.play": "Escuchar audio",
    "audio.pause": "Pausar audio",
    "audio.resume": "Reanudar audio",
    "audio.unavailable": "Audio no disponible",
    "audio.aria.listen": "Escuchar este artículo del menú",
    "audio.aria.pause": "Pausar la lectura de voz",
    "audio.aria.resume": "Reanudar la lectura de voz",
    "audio.aria.unavailable": "La lectura de voz no está disponible",
    "audio.status.ready": "Audio listo para reproducir.",
    "audio.status.playing": "Audio en reproducción.",
    "audio.status.paused": "Audio en pausa.",
    "audio.status.unavailable": "La lectura de voz no está disponible en este navegador.",
    "libras": "Lengua de señas",
    "libras.description": "Ver traducción en lengua de señas",
    "allergen.gluten": "Gluten",
    "allergen.lactose": "Lactosa",
    "allergen.nuts": "Frutos secos",
    "allergen.soy": "Soja",
    "allergen.eggs": "Huevos",
    "allergen.fish": "Pescado",
    "allergen.shellfish": "Mariscos",
    "accessibility.title": "Accesibilidad",
    "accessibility.increase_font": "Aumentar fuente",
    "accessibility.decrease_font": "Disminuir fuente",
    "accessibility.high_contrast": "Alto contraste",
    "accessibility.grayscale": "Escala de grises",
    "accessibility.dyslexia_font": "Fuente para dislexia",
    "accessibility.reset": "Restablecer",
    "accessibility.open": "Abrir accesibilidad",
    "accessibility.open.description": "Abrir panel de opciones de accesibilidad",
    "accessibility.close": "Cerrar panel de accesibilidad",
    "waiter.call": "Llamar Camarero",
    "waiter.call.table": "Llamar Camarero — Mesa",
    "waiter.called": "¡Camarero llamado!",
    "waiter.calling": "Llamando...",
    "waiter.already_called": "El camarero ya ha sido llamado para esta mesa.",
    "language": "Idioma",
    "language.options": "Opciones de idioma del menú",
    "language.select": "Seleccionar idioma del menú",
    "ingredients.image.button": "Ver ingredientes",
    "ingredients.image.aria": "Ver ingredientes como imagen:",
    "ingredients.image.loading": "Generando imagen de ingredientes...",
    "ingredients.image.error": "No se pudo generar la imagen. Inténtalo de nuevo.",
    "ingredients.image.modal.title": "Ingredientes",
    "ingredients.image.modal.close": "Cerrar modal de ingredientes",
    "ingredients.image.alt": "Ilustración de los ingredientes del plato",
    "tutorial.button": "Cómo usar",
    "tutorial.title": "Cómo usar el menú",
    "tutorial.close": "Cerrar video",
    "tutorial.play": "Reproducir video",
    "tutorial.pause": "Pausar video",
    "tutorial.stop": "Reiniciar video",
    "tutorial.mute": "Silenciar",
    "tutorial.unmute": "Activar sonido",
    "tutorial.speed": "Cambiar velocidad del video",
    "tutorial.modal.aria": "Ver video tutorial sobre cómo usar el menú accesible",
    "tutorial.prompt": "Aprende a usar el menú accesible",
    "tutorial.watchNow": "Ver ahora",
    "tutorial.later": "Después",
    "tutorial.watchNow.aria": "Ver el video sobre cómo usar el menú accesible",
    "tutorial.later.aria": "Ver después el video sobre cómo usar el menú accesible",
    "tutorial.aria.started": "Video iniciado. Use Tab para navegar en los controles.",
    "tutorial.aria.ready": "Video listo para reproducir. Use Tab para navegar en los controles.",
    "tutorial.aria.playing": "Video en reproducción.",
    "tutorial.aria.paused": "Video en pausa.",
    "tutorial.aria.stopped": "Video reiniciado.",
    "tutorial.aria.ended": "Video finalizado.",
    "tutorial.aria.controls": "Controles del reproductor de video",
    "welcome.title": "Bienvenido a Café Infinito Olhar ☕",
    "welcome.message": "Este es un menú accesible, pensado para ofrecer una experiencia más inclusiva, con recursos como audio, ajustes de visualización y navegación simplificada.",
    "welcome.videoQuestion": "¿Quieres saber cómo usar el menú?",
    "welcome.watchVideo": "Ver video explicativo",
    "welcome.goToMenu": "Ir directo al menú",
    "welcome.listen": "Escuchar mensaje de bienvenida",
    "welcome.stopListen": "Detener lectura",
    "welcome.close": "Cerrar bienvenida",
    "welcome.watchVideo.aria": "Ver el video sobre cómo usar el menú",
    "welcome.goToMenu.aria": "Ir directo al menú",
    "welcome.modal.aria": "Pantalla de bienvenida de Café Infinito Olhar",
    "filter.aria.label": "Filtro de categorías del menú",
    "filter.aria.all": "Ver todos los artículos del menú",
    "ingredients.image.figure_alt": "Imagen con los ingredientes del plato",
    "accessibility.enabled": "activado",
    "accessibility.disabled": "desactivado",
    "accessibility.font_size": "Tamaño de fuente ajustado a",
    "accessibility.reset.done": "Configuración de accesibilidad restablecida",
  },
  fr: {
    "header.title": "Menu Accessible",
    "header.table": "Table",
    "category.entrada": "Entrées",
    "category.prato": "Plats Principaux",
    "category.acompanhamento": "Accompagnements",
    "category.bebidas": "Boissons",
    "category.sobremesa": "Desserts",
    "category.outros": "Autres",
    "category.cafe_espresso": "Café Espresso",
    "category.chocolate": "Chocolat",
    "category.empanada_salgado": "Empanadas et Salés",
    "category.metodos_extracao": "Méthodes d'Extraction",
    "category.paulistinha": "Paulistinha",
    "category.waffles": "Gaufres",
    "category.almoco": "Déjeuner",
    "category.espresso_gelado": "Espresso Glacé",
    "category.chocolate_gelado": "Chocolat Glacé",
    "category.drinks_sem_alcool": "Boissons sans Alcool",
    "category.chai_latte": "Chai-Latte",
    "category.chas": "Thés",
    "category.drinks_especiais": "Boissons Spéciales",
    "category.cervejas": "Bières",
    "filter.all": "Tous",
    "filter.pratos": "Plats Principaux",
    "filter.findFavorite": "Trouvez votre option préférée",
    "filter.bebidas": "Boissons",
    "filter.sobremesas": "Desserts",
    "filter.outros": "Autres",
    "empty.title": "Aucun article disponible pour le moment.",
    "empty.subtitle": "Allez à /admin/gestao pour ajouter des articles.",
    "audio": "Audio",
    "audio.description": "Écouter la description de l'article du menu",
    "audio.play": "Écouter l'audio",
    "audio.pause": "Mettre en pause",
    "audio.resume": "Reprendre l'audio",
    "audio.unavailable": "Audio indisponible",
    "audio.aria.listen": "Écouter cet article du menu",
    "audio.aria.pause": "Mettre en pause la lecture vocale",
    "audio.aria.resume": "Reprendre la lecture vocale",
    "audio.aria.unavailable": "La lecture vocale n'est pas disponible",
    "audio.status.ready": "Audio prêt à être lu.",
    "audio.status.playing": "Audio en lecture.",
    "audio.status.paused": "Audio en pause.",
    "audio.status.unavailable": "La lecture vocale n'est pas disponible dans ce navigateur.",
    "libras": "Langue des signes",
    "libras.description": "Voir la traduction en langue des signes",
    "allergen.gluten": "Gluten",
    "allergen.lactose": "Lactose",
    "allergen.nuts": "Noix",
    "allergen.soy": "Soja",
    "allergen.eggs": "Œufs",
    "allergen.fish": "Poisson",
    "allergen.shellfish": "Fruits de mer",
    "accessibility.title": "Accessibilité",
    "accessibility.increase_font": "Augmenter la police",
    "accessibility.decrease_font": "Diminuer la police",
    "accessibility.high_contrast": "Contraste élevé",
    "accessibility.grayscale": "Niveaux de gris",
    "accessibility.dyslexia_font": "Police dyslexie",
    "accessibility.reset": "Réinitialiser",
    "accessibility.open": "Ouvrir accessibilité",
    "accessibility.open.description": "Ouvrir le panneau d'options d'accessibilité",
    "accessibility.close": "Fermer le panneau d'accessibilité",
    "waiter.call": "Appeler Serveur",
    "waiter.call.table": "Appeler Serveur — Table",
    "waiter.called": "Serveur appelé !",
    "waiter.calling": "Appel en cours...",
    "waiter.already_called": "Le serveur a déjà été appelé pour cette table.",
    "language": "Langue",
    "language.options": "Options de langue du menu",
    "language.select": "Sélectionner la langue du menu",
    "ingredients.image.button": "Voir les ingrédients",
    "ingredients.image.aria": "Voir les ingrédients en image :",
    "ingredients.image.loading": "Génération de l'image des ingrédients...",
    "ingredients.image.error": "Impossible de générer l'image. Réessayez.",
    "ingredients.image.modal.title": "Ingrédients",
    "ingredients.image.modal.close": "Fermer la fenêtre des ingrédients",
    "ingredients.image.alt": "Illustration des ingrédients du plat",
    "tutorial.button": "Comment utiliser",
    "tutorial.title": "Comment utiliser le menu",
    "tutorial.close": "Fermer la vidéo",
    "tutorial.play": "Lire la vidéo",
    "tutorial.pause": "Mettre en pause",
    "tutorial.stop": "Redémarrer la vidéo",
    "tutorial.mute": "Couper le son",
    "tutorial.unmute": "Activer le son",
    "tutorial.speed": "Changer la vitesse de la vidéo",
    "tutorial.modal.aria": "Regarder la vidéo explicative sur l'utilisation du menu accessible",
    "tutorial.prompt": "Découvrez comment utiliser le menu accessible",
    "tutorial.watchNow": "Voir maintenant",
    "tutorial.later": "Plus tard",
    "tutorial.watchNow.aria": "Voir la vidéo sur l'utilisation du menu accessible",
    "tutorial.later.aria": "Voir plus tard la vidéo sur l'utilisation du menu accessible",
    "tutorial.aria.started": "Vidéo démarrée. Utilisez Tab pour naviguer dans les contrôles.",
    "tutorial.aria.ready": "Vidéo prête à être lue. Utilisez Tab pour naviguer dans les contrôles.",
    "tutorial.aria.playing": "Vidéo en lecture.",
    "tutorial.aria.paused": "Vidéo en pause.",
    "tutorial.aria.stopped": "Vidéo redémarrée.",
    "tutorial.aria.ended": "Vidéo terminée.",
    "tutorial.aria.controls": "Contrôles du lecteur vidéo",
    "welcome.title": "Bienvenue au Café Infinito Olhar ☕",
    "welcome.message": "Voici un menu accessible, conçu pour offrir une expérience plus inclusive, avec des fonctionnalités telles que l'audio, des ajustements d'affichage et une navigation simplifiée.",
    "welcome.videoQuestion": "Vous voulez savoir comment utiliser le menu ?",
    "welcome.watchVideo": "Regarder la vidéo explicative",
    "welcome.goToMenu": "Aller directement au menu",
    "welcome.listen": "Écouter le message de bienvenue",
    "welcome.stopListen": "Arrêter la lecture",
    "welcome.close": "Fermer la bienvenue",
    "welcome.watchVideo.aria": "Regarder la vidéo sur l'utilisation du menu",
    "welcome.goToMenu.aria": "Aller directement au menu",
    "welcome.modal.aria": "Écran de bienvenue du Café Infinito Olhar",
    "filter.aria.label": "Filtre de catégories du menu",
    "filter.aria.all": "Voir tous les articles du menu",
    "ingredients.image.figure_alt": "Image montrant les ingrédients du plat",
    "accessibility.enabled": "activé",
    "accessibility.disabled": "désactivé",
    "accessibility.font_size": "Taille de police ajustée à",
    "accessibility.reset.done": "Paramètres d'accessibilité réinitialisés",
  },
};

const langAudioMap: Record<Language, string> = {
  pt: "pt-BR",
  en: "en-US",
  es: "es-ES",
  fr: "fr-FR",
};

const defaultLanguageContext: LanguageContextType = {
  language: defaultLanguage,
  setLanguage: () => undefined,
  t: (key: string) => translations[defaultLanguage]?.[key] || key,
};

declare global {
  var __lovableLanguageContext: Context<LanguageContextType> | undefined;
}

const LanguageContext = globalThis.__lovableLanguageContext ?? createContext<LanguageContextType>(defaultLanguageContext);

globalThis.__lovableLanguageContext = LanguageContext;

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(defaultLanguage);

  const t = useCallback(
    (key: string) => translations[language]?.[key] || translations[defaultLanguage]?.[key] || key,
    [language]
  );

  const value = useMemo(() => ({ language, setLanguage, t }), [language, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export function getAudioLang(lang: Language) {
  return langAudioMap[lang];
}
